### ISSUE TITLE
cudatoolkit v10.0 conflicts with torchvision

### ISSUE THREAD

**Issue by tchmiel** [haruiz/CvStudio#10]
When installing cudatoolkit, the following error occurs:
```
**Package cudatoolkit conflicts for:
torchvision -> pytorch[version='1.3.0.dev20191010,1.4.0.dev20191013,1.4.0.dev20191019,1.4.0.dev20191022,1.4.0.dev20191023,1.4.0.dev20191026,1.4.0.dev20191028'] -> cudatoolkit[version='>=10.1,<10.2']
cudatoolkit=10.0
pytorch -> cudatoolkit[version='>=10.1,<10.2']**

```
By following the pytorch installation instructions, this is easily resolved by increasing the cudatoolkit version to 10.1:
`conda install pytorch torchvision cudatoolkit=10.1 -c pytorch-nightly`
resolves the issue.

readme.md is just slightly out of date.

**Comment by dloperab** [comment]
Thanks @tchmiel , the readme file was corrected and be available in the next version of master branch
