### ISSUE TITLE
PyQt version

### ISSUE THREAD

**Issue by d139093** [haruiz/CvStudio#14]
So i checked the version using pip list and gave me 5.13.0 but when i ran
from PyQt5.Qt import PYQT_VERSION_STR
print("PyQt version:", PYQT_VERSION_STR)
i got an import error message that says 
builtins.ImportError: cannot import name 'PYQT_VERSION_STR' from 'PyQt5.Qt' (C:\Users\zbook\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PyQt5\Qt.pyd)

**Comment by haruiz** [comment]
@d139093 could you please share the output of this command: 
pip freeze
Additionally, mention what is you so (windows, Linux)

**Comment by haruiz** [comment]
@d139093 I just updated the instructions to install the software in the Readme file, can you please remove the conda environment and try again with that steps, this should fix the error you are getting

**Comment by d139093** [comment]
I got this with pip freeze. I'll do it later on today when I get home and
update you. Thank you for the help.
